trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    python -m venv antenv
    source antenv/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    export FLASK_APP=slack
    export FLASK_ENV=development
    flask init-db 
    gunicorn slack:app
  workingDirectory: /home/site/wwwroot
  displayName: 'Start the app'
