trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
  
- script: |
    python -m venv antenv
    source antenv/bin/activate
    pip install -r requirements.txt
    python -c "from slack.db import init_db; init_db()"
    gunicorn slack:app
  displayName: 'Install dependencies and start app'

- script: |
    export FLASK_APP=slack/__init__.py
    flask run --host=0.0.0.0
  displayName: 'Start the app'
