trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    python -m venv antenv
    source antenv/bin/activate
    pip install -r requirements.txt
    gunicorn app:app -b 0.0.0.0:8080
  displayName: 'Install dependencies and start app'
