trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true

- script: |
    python -m venv antenv
    source antenv/bin/activate
    pip install -r requirements.txt
    chmod +x app.sh
    ./app.sh init-db
    ./app.sh
  displayName: 'Install dependencies'

- script: |
    export FLASK_APP=app.py
    flask run --host=0.0.0.0
  displayName: 'Start the app'
